from . import InstallerBackend, InstallerParams
import subprocess
import os


INNO_SCRIPT_NAME = 'inno-script'
INNO_SETUP_SCRIPT = r'''; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "{title}"
#define MyAppVersion "{version}"
#define MyAppPublisher "{publisher}"
#define MyAppExeDir "{exe_dir}"
#define MyAppExeName "{exe_name}.exe"
#define MyAppAssocName MyAppName + ""
#define MyAppAssocExt ""
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt
#define MyAppIcon "{icon}"
#define MyAppOutputFilename "{installer_fn}"
#define MyAppOutputDir "{output_dir}"
#define MyAppDefaultDirName "{install_dir_name}"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{{{{app_id}}}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppVerName={{#MyAppName}}
AppPublisher={{#MyAppPublisher}}
DefaultDirName={{autopf}}\{{#MyAppDefaultDirName}}
UninstallDisplayIcon={{app}}\{exe_name}.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir={{#MyAppOutputDir}}
OutputBaseFilename={{#MyAppOutputFilename}}
SetupIconFile={{#MyAppIcon}}
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"

[Tasks]
Name: "desktopicon"; Description: "{{cm:CreateDesktopIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"; Flags: unchecked

[Files]
Source: "{{#MyAppExeDir}}\*"; DestDir: "{{app}}"; Flags: ignoreversion
Source: "{{#MyAppExeDir}}\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{{#MyAppAssocExt}}\OpenWithProgids"; ValueType: string; ValueName: "{{#MyAppAssocKey}}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{{#MyAppAssocKey}}"; ValueType: string; ValueName: ""; ValueData: "{{#MyAppAssocName}}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{{#MyAppAssocKey}}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{{app}}\{{#MyAppExeName}},0"
Root: HKA; Subkey: "Software\Classes\{{#MyAppAssocKey}}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{{{{app}}}}\{{#MyAppExeName}}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{{#MyAppExeName}}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{{autoprograms}}\{{#MyAppName}}"; Filename: "{{app}}\{{#MyAppExeName}}"
Name: "{{autodesktop}}\{{#MyAppName}}"; Filename: "{{app}}\{{#MyAppExeName}}"; Tasks: desktopicon
Name: "{{group}}\{{#MyAppName}}"; Filename: "{{app}}\{{#MyAppExeName}}"; IconFilename: "{{#MyAppIcon}}"

[Run]
Filename: "{{app}}\{{#MyAppExeName}}"; Description: "{{cm:LaunchProgram,{{#StringChange(MyAppName, '&', '&&')}}}}"; Flags: nowait postinstall skipifsilent

[Dirs]
Name: "{{app}}"; Permissions: everyone-full'''


class InnoBackend(InstallerBackend):
    def build(self, params, output_dir, exe_dir, save_dir):
        # Create inno setup script file
        script = INNO_SETUP_SCRIPT.format(
            title=params.title,
            version=params.version,
            publisher=params.publisher,
            exe_name=os.path.join(exe_dir, f'{params.exe_name}'),
            exe_dir=exe_dir,
            icon=os.path.abspath(params.icon),
            installer_fn=params.get_installer_name(),
            install_dir_name=params.install_dir_name,
            app_id=params.app_id,
            output_dir=output_dir,
        )
        print(script)
        inno_file = f'{save_dir}/{INNO_SCRIPT_NAME}.iss'

        with open(inno_file, 'w') as f:
            f.write(script)

        # Build installer
        subprocess.run(('iscc', inno_file))

        # Clean up
        os.remove(f'{save_dir}/{INNO_SCRIPT_NAME}.iss')
